<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html lang="en">
  <head>	
   <meta http-equiv="content-type" content="text/html; charset=utf-8">

    <meta name="viewport"    content="width=device-width, initial-scale=1.0">        
    <meta name="google-site-verification" content="zMT1XPPu3wK0oDgAFnHyDXPQtjNZPjnv0GqcCFHkLew" />    
    <meta name="keywords"  content="LogisticPartners offers easy booking of luggage vehicle for transporation  withinn city limit at affordable  rates . Tranportation includes like chemical goods , consumer packages , retail, food and bevrages,etc. Delivery at exact location , and also offering one day hiring of any vehicle, Online booking , Hassle free ">	
    <meta name="description"      content="Providing tranportation for any packaging material withinn city limit. Easy to book , flexible , door to door delivery" >	
    <meta name="robots" content="noindex,nofollow">	
    <title>Logisticpartners | Providing  mini truck on rent |Providing tranportation for any packaging material withinn city limit. Easy to book , flexible , door to door delivery
    </title>
    	<link rel="shortcut icon" href="<?php echo base_url().'assets/images/favicon.png'?>">  
    <!--
    	<link rel="stylesheet" media="screen" href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,700">
    --> 
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script> 
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">     
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.0.0/css/bootstrap.min.css">  
    <link rel="stylesheet" href="<?php echo base_url().'assets/css/main.css'?>">
    <link rel="stylesheet" href="<?php echo base_url().'assets/css/bootstrap-theme.css'?>">
    <link rel="stylesheet" href="<?php echo base_url().'assets/css/sachin_css.css'?>">
    <link rel="stylesheet" href="<?php  echo base_url().'assets/css/mukul_css.css'?>">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css" />    
    <!--link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/hover.css/2.0.2/css/hover-min.css">-->          
    <!-- Google Tag Manager --> 
    <!--
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-NSV3BQ');</script> 
-->
    <!-- End Google Tag Manager -->        
  </head>  
  <body class="home">
  <!-- Go to www.addthis.com/dashboard to customize your tools --> 
  <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-58305cf17e04e616"></script> 
  <!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "WebSite",
  "name": "logisticpartners.in",
  "alternateName": "LogisticPartners offers easy booking of luggage vehicle for transporation  withinn Nagpur limit at affordable  rates . Tranportation includes like chemical goods , consumer packages , retail, food and bevrages,etc. Delivery at exact location , and also offering one day hiring of any vehicle, Online booking , Hassle free",
  "url": "http://www.logisticpartners.com"
}

</script>
<script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "SoftwareApplication",
  "name" : "LogisticPartner Delivering new solutions",
  "image" : "http://logisticpartners.in/assets/images/logo.png",
  "url" : "http://logisticpartners.in/",
  "author" : {
    "@type" : "Person",
    "name" : "contact@logisticpartners.in"
  },
  "applicationCategory" : [ "Consumer Packaged Goods", "Chemical Goods", "Food and Beverage", "Retail Goods", "Other Goods" ],
  "review" : {
    "@type" : "Review",
	"author" : {
      "@type" : "Person",
      "name" : "LogisticPartner"
    },
    "reviewBody" : "logisticpartner.in is offering On-demand Transportation solutions to all your goods, reducing the expenses / cost for the customer. Our aim to deliver quality service"
  }
}
</script>
<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "LogisticPartner",
  "image" : "http://logisticpartners.in/assets/images/logo.png",
  "telephone" : "9595116804",
  "email" : "contact@logisticpartners.in",
  "address" : {
    "@type" : "PostalAddress",
    "addressLocality" : ", Ramdaspeth",
    "addressRegion" : "Nagpur,"
  },
  "review" : {
    "@type" : "Review",
	"author" : {
      "@type" : "Person",
      "name" : "LogisticPartner"
    },
    "reviewBody" : "logisticpartner.in is offering On-demand Transportation solutions to all your goods, reducing the expenses / cost for the customer. Our aim to deliver quality service"
  }
}
</script>
<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "ProfessionalService",
  "name" : "Logisticservices",
  "image" : "http://logisticpartners.in/assets/images/logo.png",
  "additionalType" : "http://logisticpartners.in",
  "address" : {
  "@type" : "PostalAddress",
  "streetAddress" : "Ramddaspeth",
  "addressLocality" : "nagpur",
  "addressRegion" : "nagpur",
  "postalCode" : "440002",
  "addressCountry" : "IN"
  },
  "telephone" : "919595116804",
  "email" : "info@logisticpartnes.in"
}
</script>

    <noscript>
      <iframe src="https://www.googletagmanager.com/ns.html?id=GTM-NSV3BQ" height="0" width="0" style="display:none;visibility:hidden">
      </iframe>
    </noscript>
    
    <div id="mySidenav" class="sidenav">  
      <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>  
      <a href="#" title="about">About</a>  
      <a href="#"  title="Services">Services</a>  
      <a href="#"  title="Clients">Clients</a>  
      <a href="#"  title="Contact">Contact</a>
    </div>
    <div id="main" class="navbar navbar-inverse"  style="padding:0px"> 	
      <table width="100%" style="margin-top: -25px;">               
        <tr>                   
          <th id="h" style="text-align:center; width:13%;">
            <h1 class="lead" style="color: white;font-size: 30px  ">LogisticPartner</h1>                       
            <hr id="tag">                       
            <i style="color:white;letter-spacing: 1.5px;      font-family: initial;      font-size: 15px;">Delivering new solutions</i>                
          </th>                   
          <th id="hh"  style="text-align:center;width:73%">                      
            <a title="LogisticPartners">
              <img src="<?php echo base_url().'assets/images/logo.png'?>" style="padding-top:35px;" alt="LogisticPartners"></a>                   
          </th>                 
          <th id="hhh"style="      color: white;      text-align: center;   ">
            <span style="cursor:pointer" onclick="openNav()">
              <h1  class="lead" style="font-size:50px">&#9776</h1>
            </span>
          </th>                
        </tr>                               
      </table>
    </div></h1></h1>
<script>
function openNav() {
    document.getElementById("mySidenav").style.width = "250px";
    document.getElementById("main").style.marginLeft = "250px";
    document.getElementById("whatwemove").style.marginLeft = "250px";	
    document.getElementById("footer").style.marginLeft = "250px";
    document.body.style.backgroundColor = "rgba(0,0,0,0.4)";
}
function closeNav() {
    document.getElementById("mySidenav").style.width = "0";
    document.getElementById("main").style.marginLeft= "0";
    document.getElementById("whatwemove").style.marginLeft= "0";	
    document.getElementById("footer").style.marginLeft= "0";	
    document.body.style.backgroundColor = "white";
}
</script>